language: generic 
sudo: required
services:
    - docker
before_install:
    - docker build -t seethroughlab/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true seethroughlab/react-test npm test

after_success:
    - docker build -t seethroughlab/multi-client ./client
    - docker build -t seethroughlab/multi-server ./server
    - docker build -t seethroughlab/multi-nginx ./nginx
    - docker build -t seethroughlab/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push seethroughlab/multi-client
    - docker push seethroughlab/multi-server
    - docker push seethroughlab/multi-nginx
    - docker push seethroughlab/multi-worker
